seatyourself/config/routes.rb
Seatyourself::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :users
  resources :sessions
  resources :restaurants do
    resources :reservations, :except => [:index]  
  end 
  root :to => "restaurants#index"

end

seatyourself/app/models/person.rb
class Person < ActiveRecord::Base
  authenticates_with_sorcery!
end

seatyourself/app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant

	validates_numericality_of :guests
	validates_numericality_of :time_slot

end

seatyourself/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :users, :through => :reservations
end

seatyourself/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  has_many :reservations
  has_many :restaurants, :through => :reservations

end

seatyourself/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception 
end

seatyourself/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user_id = current_user.id
  
    if @reservation.save
      redirect_to :root, :notice => "Reservation Made!"
    else
      render :template => 'restaurants/show'
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update_attributes(reservation_params)
      redirect_to reservation_path(@reservation)
    else
      render :edit
    end
  end

  def show

  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_path
  end

  private
  def reservation_params
    params.require(:reservation).permit(:user_id, :time_slot, :guests, :restaurant_id)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

seatyourself/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurant = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])

    if current_user
      @reservation = @restaurant.reservations.build
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

      if @restaurant.save
        redirect_to restaurants_path(@restaurant)
      else
        render :new
      end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(restaurant_params)
        redirect_to restaurant_path(@restaurant)
    else
        render :edit   
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :location, :address, :hours)
  end
end

  

seatyourself/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = login(params[:email], params[:password], params[:remember_me])
  	if user
  		redirect_back_or_to root_url, :notice => "Logged in!"
  	else
  		flash.now.alert = "Email or password was invalid"
  		render :new
    end
  end

  def destroy
  	logout
  	redirect_to root_url, :notice => "Logged out"
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

seatyourself/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to root_url, :notice => "Signed up!"
  	else
  		render :new
  	end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

seatyourself/app/helpers/application_helper.rb
module ApplicationHelper
end

seatyourself/app/helpers/reservations_helper.rb
module ReservationsHelper
end

seatyourself/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

seatyourself/app/helpers/sessions_helper.rb
module SessionsHelper
end

seatyourself/app/helpers/users_helper.rb
module UsersHelper
end

seatyourself/app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-brand"><%= link_to "SeatYourself", root_path %></div>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><p class= "navbar-text">Logged in as <%= current_user.email %></p></li>
        <li><%= link_to "Log out", logout_path %></li>
      <% else %>
        <li><%= link_to "Sign up", signup_path %></li>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

seatyourself/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seatyourself</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

		<% flash.each do |name, msg| %>
			<% content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>

		<% if flash[:notice] %>
			<div class="alert alert-info"><%= flash[:notice] %></div>
		<% end %>
		<% if flash[:alert] %>
			<div class="alert alert-warning"%><%= flash[:alert]%></div>
		<% end %>

<div class="container">	
	<%= yield %>
</div>
	

</body>
</html>

seatyourself/app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

seatyourself/app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

seatyourself/app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

seatyourself/app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

seatyourself/app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

seatyourself/app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

seatyourself/app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

seatyourself/app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

seatyourself/app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

seatyourself/app/views/restaurants/index.html.erb
<div class="jumbotron">
  <h1>"Please wait to be seated"</h1>
    <p>Standing at the door waiting for a vibrator telling you when a table is available sucks. Show the wait staff at your favourite restaurant how to do their job. Pick a restaurant, choose how many friends you want to bring, and SeatYourself.</p>
    <p>Don't see the restaurant you want? Add it.</p>
    <div class="btn btn-default btn-md"><%= link_to "New Restaurant", new_restaurant_path %></div>
</div>

 

<% @restaurant.each do |restaurant| %>
  <div class="rest">
    <div class="thumbnail">
      <div class="caption">
        <h2><%= link_to restaurant.name, restaurant %></h2>
        <p><%= restaurant.address %></p>
        <p><%= restaurant.location %></p>
        <p><%= restaurant.hours %></p>
      </div>
    </div>
  </div>
<% end %>

seatyourself/app/views/restaurants/new.html.erb
<% if current_user %> 
  <%= form_for @restaurant do |f| %>
    <p>
      <%= f.label "Name" %><br>
      <%= f.text_field "name" %>
    </p>
     <p>
      <%= f.label "Address" %><br>
      <%= f.text_field "address" %>
    </p>
      <%= f.label "Location" %><br>
      <%= f.text_field "location" %>
    </p>
    <p>
      <%= f.label "Total Capacity" %><br>
      <%= f.number_field 'capacity', :max => 100 %>
    </p>
    <p>
      <%= f.submit "Save" %> 
    </p>
  <% end %>
<% else %>
  <p>Please <%= link_to "Log in", login_path %> to make a Restaurant.</p>
<% end %>
<%= link_to 'Back', restaurants_path %>

seatyourself/app/views/restaurants/show.html.erb
<%= link_to 'Delete Restaurant', @restaurant, :confirm => "Delete this Restaurant?", :method => :delete %>

<h1 class=><%= @restaurant.name %></h1>
	<p>
		<%= @restaurant.address %>
		<%= @restaurant.location %>
		<br>
		<%= @restaurant.hours %>
	</p>

<% if current_user %> 

<%= form_for ([@restaurant, @reservation]) do |f| %>
	<% if @reservation.errors.any? %>
		<div id="error_explanation">
	        <h2><%= pluralize(@reservation.errors.count, "error") %> 
	        		prohibited this reservation from being saved:</h2>
	        <ul>
		        <% @reservation.errors.full_messages.each do |msg| %>
		        	<li><%= msg %></li>
		        <% end %>
        	</ul>
    	</div>
    <% end %>  
	
	<div class="field">
		<%= f.label 'Guest' %><br>
		<%= f.number_field 'guests', :max => 100 %>
	</div>

	<div class="field">
		<%= f.label 'Time' %><br>
		<%= f.number_field 'time_slot', in: 12..22 %>
	</div>	
		<%= f.submit 'Save' %>
	<% end %>
<% end %>



<%= link_to 'Back', restaurants_path %>

seatyourself/app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

seatyourself/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid!</h2>
		<ul>
			<% for message in @user.errors.full_messages %>
				<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %><br>
	</div>
	<div class='actions'><%= f.submit %></div>
<% end %>